services:
  db:
    profiles: [dev, test]
    image: postgres:latest
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      # mount script to run during database initialization
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Used to check if db is up before starting api containers
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testdb -U myuser"]
      interval: 1s
      timeout:  5s
      retries: 5

  # Run API service using dev db
  api_dev:
    profiles: [dev]
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    # Load environment variables from dev.env
    env_file: dev.env
    # Expose ports from <host>:<container>
    ports:
      - "8080:8080"
    depends_on:
      # Make sure db is up before running api_dev service
      db:
        condition: service_healthy

  # Run API service using prod db
  api_prod:
    profiles: [prod]
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    command: ["/app/main", "-env=prod"]
    env_file: prod.env
    ports:
      - "8080:8080"

  # Run API tests on dev db
  api_test:
    profiles: [test]
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    # Overwrite Dockerfile command with the test command
    command: ["go", "test", "./..."]
    env_file: dev.env
    depends_on:
      db:
        condition: service_healthy
   
  frontend:
    profiles: [dev, test]
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy

