// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/brothers": {
            "get": {
                "description": "Get data from all Brother records in ` + "`" + `Brothers` + "`" + ` table",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get all Brothers data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Brother"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Brother record row for ` + "`" + `Brothers` + "`" + ` table",
                "tags": [
                    "Brothers"
                ],
                "summary": "Create Brother record",
                "parameters": [
                    {
                        "description": "Values for new record",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Brother"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/brothers/count": {
            "get": {
                "description": "Get major distribution counts across all members",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get total Brothers count",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/brothers/majors/count": {
            "get": {
                "description": "Get major distribution counts across all members",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get major counts",
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetBrotherStatusCount.SemesterCount"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/brothers/statuses": {
            "get": {
                "description": "Get all status records per brother",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get all status records per brother",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Semester filter",
                        "name": "semester",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BrotherStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/brothers/statuses/count": {
            "get": {
                "description": "Get status counts for all semesters",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get status counts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetBrotherStatusCount.SemesterCount"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/brothers/{id}": {
            "get": {
                "description": "Get Brother record by ID",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get Brother record by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Brother ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update one or more fields for Brother record",
                "tags": [
                    "Brothers"
                ],
                "summary": "Update Brother record",
                "parameters": [
                    {
                        "description": "Values to update for Brother",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Brother"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Brother with by Roll Call",
                "tags": [
                    "Brothers"
                ],
                "summary": "Delete Brother by Roll Call",
                "parameters": [
                    {
                        "description": "RollCall of Brother",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/brothers/{id}/statuses": {
            "get": {
                "description": "Get all status recorded for Brother",
                "tags": [
                    "Brothers"
                ],
                "summary": "Get status history of a Brother",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Brother ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new status record for a Brother",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Brothers"
                ],
                "summary": "Create status record for Brother",
                "parameters": [
                    {
                        "description": "Values for new record",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateBrotherStatus.RequestBody"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Brother ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "description": "Get data from all rows in events table",
                "tags": [
                    "Events"
                ],
                "summary": "Get all event records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Event"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update event record by eventID",
                "tags": [
                    "Events"
                ],
                "summary": "Update event record",
                "parameters": [
                    {
                        "description": "Event ID",
                        "name": "eventid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Event"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new event record",
                "tags": [
                    "Events"
                ],
                "summary": "Create new event record",
                "parameters": [
                    {
                        "description": "Values for new event record",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Event"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/events/{eventid}": {
            "get": {
                "description": "Get event information by eventID",
                "tags": [
                    "Events"
                ],
                "summary": "Get event data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "eventid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Event"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/events/{eventid}/attendance": {
            "get": {
                "description": "Get event and attendance data by eventID",
                "tags": [
                    "Events"
                ],
                "summary": "Get event and attendance data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "eventid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetEventAttendance.EventDataAndAttendance"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/statuses": {
            "get": {
                "description": "Get all valid status labels (e.g.: \"Active\")",
                "tags": [
                    "Statuses"
                ],
                "summary": "Get status labels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateBrotherStatus.RequestBody": {
            "type": "object",
            "properties": {
                "brotherID": {
                    "type": "integer"
                },
                "semesterID": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.GetBrotherStatusCount.SemesterCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "handlers.GetEventAttendance.EventDataAndAttendance": {
            "type": "object",
            "properties": {
                "attendance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EventAttendance"
                    }
                },
                "eventCategory": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "eventID": {
                    "description": "primary",
                    "type": "integer"
                },
                "eventLocation": {
                    "type": "string"
                },
                "eventName": {
                    "type": "string"
                }
            }
        },
        "models.APIResponse": {
            "description": "JSON response format for all API calls",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Omit if nil"
                },
                "message": {
                    "description": "Omit if nil",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Brother": {
            "description": "Brother information",
            "type": "object",
            "required": [
                "firstName",
                "lastName",
                "major",
                "rollCall",
                "status"
            ],
            "properties": {
                "badStanding": {
                    "type": "integer"
                },
                "brotherID": {
                    "description": "Primary Key",
                    "type": "integer"
                },
                "className": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "rollCall": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.BrotherStatus": {
            "description": "Brother Status information for a semester",
            "type": "object",
            "properties": {
                "brotherID": {
                    "type": "integer"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "rollCall": {
                    "type": "string"
                },
                "semesterLabel": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Event": {
            "description": "Event information",
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "eventID": {
                    "description": "primary",
                    "type": "integer"
                },
                "eventLocation": {
                    "type": "string"
                },
                "eventName": {
                    "type": "string"
                }
            }
        },
        "models.EventAttendance": {
            "description": "Event Attendance information of a Brother",
            "type": "object",
            "properties": {
                "attendanceStatus": {
                    "type": "string"
                },
                "brotherID": {
                    "type": "integer"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "rollCall": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
